server:
  port: 8003
  servlet:
    context-path: /feign-client

spring:
  application:
    name: feign-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka,http://eureka-server7002:7002/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 7
    hostname: localhost
    instance-id: feign-client
feign:
  hystrix:
    enabled: true
