server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuth1018/cloud-demo
          search-paths: config
          username: 2624235265@qq.com
          password: qq101896

eureka:
  instance:
    hostname: localhost
    instance-id: config-server
  client:
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka,http://eureka-server7002:7002/eureka
