server:
  port: 9001


eureka:
  instance:
    hostname: localhost
    instance-id: config-server
    lease-expiration-duration-in-seconds: 7
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka,http://eureka-server7002:7002/eureka
    registry-fetch-interval-seconds: 5