server:
  port: 9001

spring:
  application:
    name: zuul-api
eureka:
  instance:
    hostname: zuul-api9001
    instance-id: zuul-api9001
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 7
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://eureka-server7002:7002/eureka/,http://eureka-server7001:7001/eureka/
zuul:
  ignored-services:  "*"   #忽略指定微服务 *：所有
  ignored-patterns: /**/user/*  #忽略所有包含user的地址请求
  routes: #路由匹配规则  serviceid -> 自定义
    eureka-client: /client/**

  ZuulDemoFilter:
    pre:
      disable: true
