server:
  port: 9001
  servlet:
    context-path: /ribbon-client

spring:
  application:
    name: ribbon-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka,http://eureka-server7002:7002/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ribbon-client
    hostname: localhost
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 7